FROM kalilinux/kali-rolling:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        wireshark \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* 
