name: Build Wireshark

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # every day at midnight
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./distrobox/wireshark
          file: ./distrobox/wireshark/Containerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:latest
